#!/bin/bash
#SBATCH --job-name=CellAnger
#SBATCH --nodes=1
#SBATCH --cpus-per-task=16
#SBATCH --mem=64G
#SBATCH --time=12:00:00
#SBATCH --output=/lisc/data/scratch/course/2025w300106/filimonova/logs/ncellranger.%j.log
#SBATCH --error=/lisc/data/scratch/course/2025w300106/filimonova/logs/ncellranger.%j.err
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=daria.filimonova@univie.ac.at

## ENVIRONMENT
module load  CellRanger
module list

## VARIABLES
wd="/lisc/data/scratch/course/2025w300106"
indexDir="${wd}/common/NV2_fluo"
fastqDir="${wd}/common/blastula.12h/run1,${wd}/common/blastula.12h/run2,${wd}/common/blastula.12h/run3"
sample="89085" ## read all the fastq files with sample name including 89085
id="blastula_12h"

###EXECUTION
mkdir -p ${wd}/filimonova/cellranger
cd ${wd}/filimonova/cellranger
cellranger count --localcores 16 --transcriptome $indexDir --fastqs $fastqDir --id $id --sample $sample --create-bam false --force-cells 10000 --nosecondary

### Comments
# Generating a matrix for input into Seurat from raw data
# force-cells 10 000: count until reaching 10K cells (that's what we expect from our data, Huan's preference). The default might be too strict?
# nosecondary : Disable secondary analysis, e.g. clustering (not for sc)
#--chemistry threeprime: defaults would guess 
#--create-bam false: usually we just need the matrix
