#!/bin/bash
#SBATCH --job-name=STAR
#SBATCH --nodes=1
#SBATCH --cpus-per-task=16
#SBATCH --mem=20G
#SBATCH --time=12:00:00
#SBATCH --output=/lisc/data/scratch/course/2025w300106/filimonova/logs/STAR_trimmed.%j.log
#SBATCH --error=/lisc/data/scratch/course/2025w300106/filimonova/logs/STAR_trimmed.%j.err
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=daria.filimonova@univie.ac.at

module load STAR
module list

STAR --runThreadN 16 --genomeDir /lisc/data/scratch/course/2025w300106/filimonova/jmontenegro/Nv2genome_STAR --readFilesIn /lisc/data/scratch/course/2025w300106/filimonova/jmontenegro/trimmomatic/result/SRR23260644_1P.fastq /lisc/data/scratch/course/2025w300106/filimonova/jmontenegro/trimmomatic/result/SRR23260644_2P.fastq --outFileNamePrefix /lisc/data/scratch/course/2025w300106/filimonova/results/map/SRR23260644_trimmed --outSAMstrandField intronMotif --outSAMtype BAM SortedByCoordinate

