#!/bin/bash
#SBATCH --job-name=stringtie
#SBATCH --nodes=1
#SBATCH --cpus-per-task=2
#SBATCH --mem=2G
#SBATCH --time=1:00:00
#SBATCH --output=/lisc/data/scratch/course/2025w300106/filimonova/logs/stringtie.%j.log
#SBATCH --error=/lisc/data/scratch/course/2025w300106/filimonova/logs/stringtie.%j.err
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=daria.filimonova@univie.ac.at


module load StringTie
module list

stringtie -p 4 -m 10 -v -i -l -o GeneModelsGeneratedStringTie -j 5 -g 200 -N --nasc ./results/map/SRR23260644_trimmedAligned.sortedByCoord.filtered_2.out.bam 

### Comments
# Generating gene models using Stringtie
# changed -m  minimal lenght from 30 to 10 (short reads because nascent RNA library) 
# --nasc for nascent transcipts
# -N for non-polyA RNA
# -i 	keep transcripts with predicted unsplices introns (our rnas are nascent. also we do not want to remove lncRNA or rely too much on prediction?)
# -j 5 Only keep splice junctions that are supported by at least 5 reads (Huan's preference)
# -g 200 minimal locus separation distance (Huan´s preference) 
# -p threads (4)
# -v verbose
# -l label (output prefix) ???
