#!/bin/bash
#SBATCH --job-name=featureCounts
#SBATCH --nodes=1
#SBATCH --cpus-per-task=2
#SBATCH --mem=2G
#SBATCH --time=1:00:00
#SBATCH --output=/lisc/data/scratch/course/2025w300106/filimonova/logs/qc_featureCounts.%j.log
#SBATCH --error=/lisc/data/scratch/course/2025w300106/filimonova/logs/qc_featureCounts.%j.err
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=daria.filimonova@univie.ac.at

### ENVIRONMENT
module load Subread
module list

### VARIABLES
genemodels="/lisc/data/scratch/course/2025w300106/filimonova/results/map/GeneModelsGeneratedStringTie.gtf" #forgot to limit to multi-exon
#genemodels="/lisc/data/scratch/course/2025w300106/filimonova/results/map/filtered_gene_models.gtf" those for sanity checking if mine are too short to map
aligned_reads="/lisc/data/scratch/course/2025w300106/filimonova/results/map/SRR23260644_trimmedAligned.sortedByCoord.filtered_2.out.bam"

### EXECUTION

featureCounts -a $genemodels -t exon -g gene_id -s 1 -p --primary -T 4 -o ./results/featurecount_SRR23260644.tsv $aligned_reads

### Comments
# QC for my StringTie results
# -s 1: PRO-seq libraries are normally forward-stranded
# -p: my reads are paired
# my mapped reads are 0% and I unfortunately could not find out why. Switching to other dataset because it was very short anyway.
